---

- name: Make sure NetworkManager is started at boot
  shell: systemctl enable NetworkManager

- name: Make sure that nothing usurps Network Manager
  shell: systemctl mask network

- name: Configurate networks
  template:
    src: etc/network/interfaces.j2
    dest: /etc/network/interfaces
